blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/planetabhi/mfi/discussions
    about: Please use discussions for questions, feedback, and general conversations
