blank_issues_enabled: false
contact_links:
  - name: Questions & discussions
    url: https://github.com/planetabhi/makeforindia.com/discussions
    about: Please use discussions for questions, feedback, and general conversations
